In [ ]:
import torch
from torch import nn
from torch import optim
from torch.utils.data import TensorDataset, DataLoader 

train_x = torch.FloatTensor([
    [1, 2], [2, 3], [3, 4], [4, 5], [5, 6], [6, 7]
])
train_y = torch.FloatTensor([
    [0.1, 1.5], [1, 2.8], [1.9, 4.1], [2.8, 5.4], [3.7, 6.7], [4.6, 8]
])

In [2]:
train_dataset = TensorDataset(train_x, train_y)
train_dataloader = DataLoader(train_dataset, batch_size=2, shuffle=True, drop_last=True)

In [3]:
model = nn.Linear(2, 2, bias=True)
criterion = nn.MSELoss()
optimizer = optim.SGD(model.parameters(), lr=0.001)

In [ ]:
for epoch in range(20000):
    cost = 0.0
    
    for batch in train_dataloader:
        x, y = batch
        output = model(x)
        
        loss = criterion(output, y)
        
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
        
        cost += loss

    cost = cost / len(train_dataloader)
    
    if (epoch + 1) % 1000 == 0:
        print(f"Epoch : {epoch+1:4d}, Model : {list(model.parameters())}, Cost : {cost:.3f}")

Epoch : 1000, Model : [Parameter containing:
tensor([[0.7778, 0.0372],
        [0.5955, 0.5971]], requires_grad=True), Parameter containing:
tensor([-0.4786,  0.0561], requires_grad=True)], Cost : 0.033
Epoch : 2000, Model : [Parameter containing:
tensor([[ 0.8642, -0.0075],
        [ 0.7047,  0.5405]], requires_grad=True), Parameter containing:
tensor([-0.6098, -0.1096], requires_grad=True)], Cost : 0.008
Epoch : 3000, Model : [Parameter containing:
tensor([[ 0.9082, -0.0304],
        [ 0.7603,  0.5117]], requires_grad=True), Parameter containing:
tensor([-0.6766, -0.1941], requires_grad=True)], Cost : 0.002
Epoch : 4000, Model : [Parameter containing:
tensor([[ 0.9307, -0.0419],
        [ 0.7887,  0.4970]], requires_grad=True), Parameter containing:
tensor([-0.7106, -0.2371], requires_grad=True)], Cost : 0.001
Epoch : 5000, Model : [Parameter containing:
tensor([[ 0.9421, -0.0479],
        [ 0.8032,  0.4896]], requires_grad=True), Parameter containing:
tensor([-0.7280, -0.2590], requ