In [1]:
import torch
from torch import nn
from torch import optim
from torch.utils.data import TensorDataset, DataLoader 

train_x = torch.FloatTensor([
    [1, 2], [2, 3], [3, 4], [4, 5], [5, 6], [6, 7]
])
train_y = torch.FloatTensor([
    [0.1, 1.5], [1, 2.8], [1.9, 4.1], [2.8, 5.4], [3.7, 6.7], [4.6, 8]
])

In [2]:
train_dataset = TensorDataset(train_x, train_y)
train_dataloader = DataLoader(train_dataset, batch_size=2, shuffle=True, drop_last=True)

In [3]:
model = nn.Linear(2, 2, bias=False)
criterion = nn.MSELoss()
optimizer = optim.SGD(model.parameters(), lr=0.001)

In [4]:
for epoch in range(20000):
    cost = 0.0
    
    for batch in train_dataloader:
        x, y = batch
        output = model(x)
        
        loss = criterion(output, y)
        
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
        
        cost += loss

    cost = cost / len(train_dataloader)
    
    if (epoch + 1) % 1000 == 0:
        print(f"Epoch : {epoch+1:4d}, Model : {list(model.parameters())}, Cost : {cost:.3f}")

Epoch : 1000, Model : [Parameter containing:
tensor([[0.4134, 0.2401],
        [0.8508, 0.4015]], requires_grad=True)], Cost : 0.109
Epoch : 2000, Model : [Parameter containing:
tensor([[0.6776, 0.0268],
        [0.9020, 0.3602]], requires_grad=True)], Cost : 0.069
Epoch : 3000, Model : [Parameter containing:
tensor([[ 0.8875, -0.1428],
        [ 0.9426,  0.3273]], requires_grad=True)], Cost : 0.044
Epoch : 4000, Model : [Parameter containing:
tensor([[ 1.0544, -0.2776],
        [ 0.9749,  0.3012]], requires_grad=True)], Cost : 0.028
Epoch : 5000, Model : [Parameter containing:
tensor([[ 1.1868, -0.3849],
        [ 1.0006,  0.2804]], requires_grad=True)], Cost : 0.018
Epoch : 6000, Model : [Parameter containing:
tensor([[ 1.2921, -0.4702],
        [ 1.0210,  0.2639]], requires_grad=True)], Cost : 0.011
Epoch : 7000, Model : [Parameter containing:
tensor([[ 1.3758, -0.5378],
        [ 1.0372,  0.2508]], requires_grad=True)], Cost : 0.007
Epoch : 8000, Model : [Parameter containing:
tens