In [1]:
import torch

device = "cuda" if torch.cuda.is_available() else "cpu"
cpu = torch.FloatTensor([1, 2, 3])
#gpu = torch.cuda.FloatTensor([1, 2, 3])
tensor = torch.rand((1, 1), device=device)
print(device)
print(cpu)
#print(gpu)
print(tensor)

cpu
tensor([1., 2., 3.])
tensor([[0.4281]])


In [ ]:
# 애플 실리콘이 탑재된 맥 사용자의 경우
import torch


device = "mps" if torch.backends.mps.is_available() and torch.backends.mps.is_built() else "cpu"
cpu = torch.FloatTensor([1, 2, 3])
mps = torch.rand((1, 1), device=device)
print(device)
print(mps)

mps
tensor([[0.7068]], device='mps:0')
