In [1]:
import torch
from torch import nn
from torch import optim
from torch.utils.data import TensorDataset, DataLoader

train_x = torch.FloatTensor([
    [1, 2], [2, 3], [3, 4], [4, 5], [5, 6], [6, 7]
])
train_y = torch.FloatTensor([
    [0.1, 1.5], [1, 2.8], [1.9, 4.1], [2.8, 5.4], [3.7, 6.7], [4.6, 8]
])

In [2]:
train_dataset = TensorDataset(train_x, train_y)
train_dataloader = DataLoader(train_dataset, batch_size=2, shuffle=True, drop_last=True)

In [3]:
model = nn.Linear(2, 2, bias=False)
criterion = nn.MSELoss()
optimizer = optim.SGD(model.parameters(), lr=0.001)

In [4]:
for epoch in range(20000):
    cost = 0.0

    for batch in train_dataloader:
        x, y = batch
        output = model(x)

        loss = criterion(output, y)

        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        cost += loss

    cost = cost / len(train_dataloader)

    if (epoch + 1) % 1000 == 0:
        print(f"Epoch : {epoch+1:4d}, Model : {list(model.parameters())}, Cost : {cost:.3f}")

Epoch : 1000, Model : [Parameter containing:
tensor([[0.5155, 0.1576],
        [0.3915, 0.7729]], requires_grad=True)], Cost : 0.121
Epoch : 2000, Model : [Parameter containing:
tensor([[ 0.7587, -0.0388],
        [ 0.5369,  0.6554]], requires_grad=True)], Cost : 0.076
Epoch : 3000, Model : [Parameter containing:
tensor([[ 0.9520, -0.1949],
        [ 0.6526,  0.5620]], requires_grad=True)], Cost : 0.049
Epoch : 4000, Model : [Parameter containing:
tensor([[ 1.1053, -0.3194],
        [ 0.7443,  0.4875]], requires_grad=True)], Cost : 0.031
Epoch : 5000, Model : [Parameter containing:
tensor([[ 1.2274, -0.4180],
        [ 0.8173,  0.4285]], requires_grad=True)], Cost : 0.019
Epoch : 6000, Model : [Parameter containing:
tensor([[ 1.3244, -0.4963],
        [ 0.8753,  0.3817]], requires_grad=True)], Cost : 0.012
Epoch : 7000, Model : [Parameter containing:
tensor([[ 1.4015, -0.5587],
        [ 0.9215,  0.3444]], requires_grad=True)], Cost : 0.008
Epoch : 8000, Model : [Parameter containing:
