In [1]:
##################
# 1. 기본 구조 선언
import torch
from torch import nn
from torch import optim
from torch.utils.data import TensorDataset, DataLoader

train_x = torch.FloatTensor([
    [1, 2], [2, 3], [3, 4], [4, 5], [5, 6], [6, 7]
])
train_y = torch.FloatTensor([
    [0.1, 1.5], [1, 2.8], [1.9, 4.1], [2.8, 5.4], [3.7, 6.7], [4.6, 8]
])

In [2]:
##################
# 2. 데이터세트와 데이터로더
train_dataset = TensorDataset(train_x, train_y)
train_dataloader = DataLoader(train_dataset, batch_size=2, shuffle=True, drop_last=True)

In [3]:
##################
# 3. 모델, 오차 함수, 최적화 함수 선언
model = nn.Linear(2, 2, bias=True)
criterion = nn.MSELoss()
optimizer = optim.SGD(model.parameters(), lr=0.001)

In [4]:
##################
# 4. 데이터로더 적용
for epoch in range(20000):
    cost = 0.0

    for batch in train_dataloader:
        x, y = batch
        output = model(x)

        loss = criterion(output, y)

        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        cost += loss

    cost = cost / len(train_dataloader)

    if (epoch + 1) % 1000 == 0:
        print(f"Epoch : {epoch+1:4d}, Model : {list(model.parameters())}, Cost : {cost:.3f}")

Epoch : 1000, Model : [Parameter containing:
tensor([[ 0.8567, -0.0926],
        [ 0.8172,  0.4661]], requires_grad=True), Parameter containing:
tensor([-0.1352, -0.1959], requires_grad=True)], Cost : 0.032
Epoch : 2000, Model : [Parameter containing:
tensor([[ 0.9947, -0.1639],
        [ 0.8341,  0.4574]], requires_grad=True), Parameter containing:
tensor([-0.3446, -0.2216], requires_grad=True)], Cost : 0.008
Epoch : 3000, Model : [Parameter containing:
tensor([[ 1.0650, -0.2002],
        [ 0.8428,  0.4529]], requires_grad=True), Parameter containing:
tensor([-0.4512, -0.2347], requires_grad=True)], Cost : 0.002
Epoch : 4000, Model : [Parameter containing:
tensor([[ 1.1008, -0.2188],
        [ 0.8472,  0.4506]], requires_grad=True), Parameter containing:
tensor([-0.5056, -0.2413], requires_grad=True)], Cost : 0.001
Epoch : 5000, Model : [Parameter containing:
tensor([[ 1.1191, -0.2282],
        [ 0.8494,  0.4495]], requires_grad=True), Parameter containing:
tensor([-0.5332, -0.2447], 