In [ ]:
import torch
from torch import nn
from torch import optim


class CustomModel(nn.Module):
    def __init__(self):
        super().__init__()

        self.layer1 = nn.Sequential(
            nn.Linear(2, 2),
            nn.Sigmoid()
        )
        
        self.layer2 = nn.Sequential(
            nn.Linear(2, 1),
            nn.Sigmoid()
        )
        
        self.layer1[0].weight.data = torch.nn.Parameter(
            torch.Tensor([[0.4352, 0.3545],
                         [0.1951, 0.4835]])
        )

        self.layer1[0].bias.data = torch.nn.Parameter(
            torch.Tensor([-0.1419,  0.0439])
        )

        self.layer2[0].weight.data = torch.nn.Parameter(
            torch.Tensor([[-0.1725,  0.1129]])
        )

        self.layer2[0].bias.data = torch.nn.Parameter(
            torch.Tensor([-0.3043])
        )

device = "cuda" if torch.cuda.is_available() else "cpu"
model = CustomModel().to(device)
criterion = nn.BCELoss().to(device)
optimizer = optim.SGD(model.parameters(), lr=1)

print(model)
for name, param in model.named_parameters():
    print(f"{name}:\n{param}\n")

CustomModel(
  (layer1): Sequential(
    (0): Linear(in_features=2, out_features=2, bias=True)
    (1): Sigmoid()
  )
  (layer2): Sequential(
    (0): Linear(in_features=2, out_features=1, bias=True)
    (1): Sigmoid()
  )
)
layer1.0.weight:
Parameter containing:
tensor([[0.4352, 0.3545],
        [0.1951, 0.4835]], requires_grad=True)

layer1.0.bias:
Parameter containing:
tensor([-0.1419,  0.0439], requires_grad=True)

layer2.0.weight:
Parameter containing:
tensor([[-0.1725,  0.1129]], requires_grad=True)

layer2.0.bias:
Parameter containing:
tensor([-0.3043], requires_grad=True)

